const getTurkishNumber = require('./')

const results = [
  'sıfır',
  'bir',
  'iki',
  'üç',
  'dört',
  'beş',
  'altı',
  'yedi',
  'sekiz',
  'dokuz',
  'on',
  'on bir',
  'on iki',
  'on üç',
  'on dört',
  'on beş',
  'on altı',
  'on yedi',
  'on sekiz',
  'on dokuz',
  'yirmi',
  'yirmi bir',
  'yirmi iki',
  'yirmi üç',
  'yirmi dört',
  'yirmi beş',
  'yirmi altı',
  'yirmi yedi',
  'yirmi sekiz',
  'yirmi dokuz',
  'otuz',
  'otuz bir',
  'otuz iki',
  'otuz üç',
  'otuz dört',
  'otuz beş',
  'otuz altı',
  'otuz yedi',
  'otuz sekiz',
  'otuz dokuz',
  'kırk',
  'kırk bir',
  'kırk iki',
  'kırk üç',
  'kırk dört',
  'kırk beş',
  'kırk altı',
  'kırk yedi',
  'kırk sekiz',
  'kırk dokuz',
  'elli',
  'elli bir',
  'elli iki',
  'elli üç',
  'elli dört',
  'elli beş',
  'elli altı',
  'elli yedi',
  'elli sekiz',
  'elli dokuz',
  'altmış',
  'altmış bir',
  'altmış iki',
  'altmış üç',
  'altmış dört',
  'altmış beş',
  'altmış altı',
  'altmış yedi',
  'altmış sekiz',
  'altmış dokuz',
  'yetmiş',
  'yetmiş bir',
  'yetmiş iki',
  'yetmiş üç',
  'yetmiş dört',
  'yetmiş beş',
  'yetmiş altı',
  'yetmiş yedi',
  'yetmiş sekiz',
  'yetmiş dokuz',
  'seksen',
  'seksen bir',
  'seksen iki',
  'seksen üç',
  'seksen dört',
  'seksen beş',
  'seksen altı',
  'seksen yedi',
  'seksen sekiz',
  'seksen dokuz',
  'doksan',
  'doksan bir',
  'doksan iki',
  'doksan üç',
  'doksan dört',
  'doksan beş',
  'doksan altı',
  'doksan yedi',
  'doksan sekiz',
  'doksan dokuz',
]

for (let i = 0; i <= 99; i++) {
  it(`${i} should return '${results[i]}'`, () => {
    const result = getTurkishNumber(i)
    expect(result).toBe(results[i])
  })
}

it('-3 should throw an error', () => {
  const result = () => getTurkishNumber(-3)
  expect(result).toThrow('Please give a number between 0 and 100.')
})

it('100 should throw an error', () => {
  const result = () => getTurkishNumber(100)
  expect(result).toThrow('Please give a number between 0 and 100.')
})
